catalogs:
  dev:
    '@biomejs/biome': ^2.1.3
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@rbxts/compiler-types': 3.0.0-types.0
    '@rbxts/types': 1.0.867
    husky: ^9.1.7
    rbxts-transformer-flamework: ^1.3.1
    license-checker: ^25.0.1
    roblox-ts: ^3.0.0
    typescript: 5.5.3
  prod:
    '@flamework/core': ^1.3.1
    '@rbxts/bytenet': 0.4.3-tsprev4
    '@rbxts/charm': ^0.10.0
    '@rbxts/log': ^0.6.3
    '@rbxts/message-templates': ^0.3.2
    '@rbxts/pretty-react-hooks': ^0.6.4
    '@rbxts/react-charm': ^0.3.0
    '@rbxts/ripple': ^0.9.3
    '@rbxts/services': ^1.5.5
    '@rbxts/set-timeout': ^1.1.2
    '@rbxts/signal': ^1.1.1
    '@rbxts/t': ^3.2.1
    '@rbxts/ui': ^0.1.0
    '@rbxts/observers': ^0.3.4
    '@rbxts/validate-tree': ^2.0.2
    '@rbxts/profile-store': ^1.0.3
    rbxts-transform-env: ^3.0.0
  react-alpha:
    '@rbxts/react': 17.3.0-alpha.1
    '@rbxts/react-roblox': 17.3.0-alpha.1

publicHoistPattern:
  - '*@rbxts*'